### ISSUE TITLE
README diagram is unreadable in GitHub's dark theme

### ISSUE THREAD

**Issue by FelSiq** [angelomenezes/face-attendance-api#1]
README diagram is unreadable in GitHub's dark theme, as shown below:

![image](https://user-images.githubusercontent.com/18670260/224694912-9af2edd6-aa61-4a01-a0ee-ee3381c2ffd6.png)

Maybe another color palette is necessary to properly accommodate both light and dark themes.

**Comment by angelomenezes** [comment]
Thanks for the feedback Felipe, that happened because it was a .png without background. I'll update it.
